name: Daily update

on:
  schedule:
    - cron: "10 7 * * *"

  workflow_dispatch:

jobs:
  make_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout script
        uses: actions/checkout@v2
