name: Daily update

on:
  push:
    branches:
      - 1-daily-update-via-github-actions
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  daily_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout script
        uses: actions/checkout@v2
