name: Daily update

on:
  schedule:
    - cron: "10 7 * * *"

  workflow_dispatch:

  push:
    branches: [ 1-daily-update-via-github-actions ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout script
        uses: actions/checkout@v2

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: dump
          path: data

      - name: Configure and start MySQL
        run: |
          echo 'secure_file_priv=""' | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo systemctl start mysql.service
          mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS dfki;'

      - name: Prepare database
        run: |
          sudo mkdir /tmp/datadir && sudo chmod 777 /tmp/datadir
          gzip -d data/rki_csv.sql.gz
          mysql --defaults-extra-file=.github/workflows/github-actions-sql.cnf dfki < data/rki_csv.sql
          rm data/rki_csv.sql

      - name: Run update
        run: |
          ./replay.sh --dir=/tmp/datadir .github/workflows/github-actions-sql.cnf

      - name: Create dump and commit
        run: |
          mysqldump --defaults-extra-file=.github/workflows/github-actions-sql.cnf dfki | gzip > data/rki_csv.sql.gz
